version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "p@ss"
      MSSQL_PID: "Express"
    ports:
     - "1433:1433" 
